# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param chipscope.maxJobs 4
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
create_project -in_memory -part xczu28dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.cache/wt [current_project]
set_property parent.project_path /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu111:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/srcs/ip/ip_repo
  /home/rafael/Documentos/RFSoC_Vivado/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_3/design_1_util_ds_buf_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_3/design_1_util_ds_buf_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_packet_detector_11AD_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_packet_detector_11AD_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_packet_detector_11AD_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_packet_detector_11AD_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/TX_Block_STA_v1_0/TX_Block_STA_v1_0.srcs/constrs_1/new/constrains.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/TX_Block_STA_v1_0/TX_Block_STA_v1_0.srcs/constrs_1/new/constrains.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/TX_Block_STA_v1_0/TX_Block_STA_v1_0.srcs/constrs_1/new/constrains.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/TX_Block_STA_v1_0/TX_Block_STA_v1_0.srcs/constrs_1/new/constrains.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/SIVERS_gpio_1.0/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/SIVERS_gpio_1.0/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/SIVERS_gpio_1.0/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_block_STA_v1_0/RX_block_STA_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/SIVERS_gpio_1.0/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_SIVERS_gpio_0_0/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/data/startup.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc
set_property used_in_implementation false [get_files /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc]

read_xdc /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xczu28dr-ffvg1517-2-e -flatten_hierarchy none -keep_equivalent_registers


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
