# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/placing_constraints.xdc

# XDC: new/timing.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_usp_rf_data_converter_0_0/design_1_usp_rf_data_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usp_rf_data_converter_0_0 || ORIG_REF_NAME==design_1_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_2 || ORIG_REF_NAME==design_1_util_ds_buf_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M_1 || ORIG_REF_NAME==design_1_rst_ps8_0_96M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_3/design_1_util_ds_buf_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_3 || ORIG_REF_NAME==design_1_util_ds_buf_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_4/design_1_sync_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_4 || ORIG_REF_NAME==design_1_sync_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_5/design_1_sync_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_5 || ORIG_REF_NAME==design_1_sync_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_3/design_1_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_3 || ORIG_REF_NAME==design_1_xlconstant_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_2/design_1_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_2 || ORIG_REF_NAME==design_1_xlconstant_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_12/design_1_sync_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_12 || ORIG_REF_NAME==design_1_sync_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M1_0 || ORIG_REF_NAME==design_1_rst_ps8_0_96M1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_13/design_1_sync_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_13 || ORIG_REF_NAME==design_1_sync_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_globalstart_gpio_0/design_1_globalstart_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_globalstart_gpio_0 || ORIG_REF_NAME==design_1_globalstart_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_2_0/design_1_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_2_0 || ORIG_REF_NAME==design_1_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_0/design_1_packet_detector_11AD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_0 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_1/design_1_packet_detector_11AD_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_1 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_3/design_1_packet_detector_11AD_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_3 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_2/design_1_packet_detector_11AD_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_2 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_17/design_1_xlslice_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_17 || ORIG_REF_NAME==design_1_xlslice_0_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_48/design_1_util_vector_logic_0_48.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_48 || ORIG_REF_NAME==design_1_util_vector_logic_0_48} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_50/design_1_util_vector_logic_0_50.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_50 || ORIG_REF_NAME==design_1_util_vector_logic_0_50} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_21/design_1_sync_0_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_21 || ORIG_REF_NAME==design_1_sync_0_21} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_15/design_1_xlconstant_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_15 || ORIG_REF_NAME==design_1_xlconstant_0_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_19/design_1_xlslice_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_19 || ORIG_REF_NAME==design_1_xlslice_0_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_52/design_1_util_vector_logic_0_52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_52 || ORIG_REF_NAME==design_1_util_vector_logic_0_52} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_8/design_1_util_vector_logic_2_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_8 || ORIG_REF_NAME==design_1_util_vector_logic_2_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_6/design_1_sync_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_6 || ORIG_REF_NAME==design_1_sync_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_17/design_1_xlconstant_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_17 || ORIG_REF_NAME==design_1_xlconstant_0_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_21/design_1_xlslice_0_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_21 || ORIG_REF_NAME==design_1_xlslice_0_21} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_54/design_1_util_vector_logic_0_54.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_54 || ORIG_REF_NAME==design_1_util_vector_logic_0_54} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_10/design_1_util_vector_logic_2_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_10 || ORIG_REF_NAME==design_1_util_vector_logic_2_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_8/design_1_sync_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_8 || ORIG_REF_NAME==design_1_sync_1_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_19/design_1_xlconstant_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_19 || ORIG_REF_NAME==design_1_xlconstant_0_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_20/design_1_xlslice_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_20 || ORIG_REF_NAME==design_1_xlslice_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_53/design_1_util_vector_logic_0_53.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_53 || ORIG_REF_NAME==design_1_util_vector_logic_0_53} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_9/design_1_util_vector_logic_2_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_9 || ORIG_REF_NAME==design_1_util_vector_logic_2_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_7/design_1_sync_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_7 || ORIG_REF_NAME==design_1_sync_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_18/design_1_xlconstant_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_18 || ORIG_REF_NAME==design_1_xlconstant_0_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_globalstart_gpio_adc_0/design_1_globalstart_gpio_adc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_globalstart_gpio_adc_0 || ORIG_REF_NAME==design_1_globalstart_gpio_adc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_9/design_1_sync_1_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_9 || ORIG_REF_NAME==design_1_sync_1_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TX_Block_STA_0_5/design_1_TX_Block_STA_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TX_Block_STA_0_5 || ORIG_REF_NAME==design_1_TX_Block_STA_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TX_Block_STA_0_3/design_1_TX_Block_STA_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TX_Block_STA_0_3 || ORIG_REF_NAME==design_1_TX_Block_STA_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TX_Block_STA_0_4/design_1_TX_Block_STA_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TX_Block_STA_0_4 || ORIG_REF_NAME==design_1_TX_Block_STA_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_TX_Block_STA_0_2/design_1_TX_Block_STA_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_TX_Block_STA_0_2 || ORIG_REF_NAME==design_1_TX_Block_STA_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_22/design_1_xlslice_0_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_22 || ORIG_REF_NAME==design_1_xlslice_0_22} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_55/design_1_util_vector_logic_0_55.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_55 || ORIG_REF_NAME==design_1_util_vector_logic_0_55} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_11/design_1_util_vector_logic_2_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_11 || ORIG_REF_NAME==design_1_util_vector_logic_2_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_10/design_1_sync_1_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_10 || ORIG_REF_NAME==design_1_sync_1_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_20/design_1_xlconstant_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_20 || ORIG_REF_NAME==design_1_xlconstant_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/design_1_RX_Block_STA_v2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RX_Block_STA_v2_0_0 || ORIG_REF_NAME==design_1_RX_Block_STA_v2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/design_1_RX_Block_STA_v2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RX_Block_STA_v2_0_1 || ORIG_REF_NAME==design_1_RX_Block_STA_v2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/design_1_RX_Block_STA_v2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RX_Block_STA_v2_0_2 || ORIG_REF_NAME==design_1_RX_Block_STA_v2_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/design_1_RX_Block_STA_v2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RX_Block_STA_v2_0_3 || ORIG_REF_NAME==design_1_RX_Block_STA_v2_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_56/design_1_util_vector_logic_0_56.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_56 || ORIG_REF_NAME==design_1_util_vector_logic_0_56} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_57/design_1_util_vector_logic_0_57.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_57 || ORIG_REF_NAME==design_1_util_vector_logic_0_57} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_58/design_1_util_vector_logic_0_58.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_58 || ORIG_REF_NAME==design_1_util_vector_logic_0_58} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_59/design_1_util_vector_logic_0_59.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_59 || ORIG_REF_NAME==design_1_util_vector_logic_0_59} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_60/design_1_util_vector_logic_0_60.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_60 || ORIG_REF_NAME==design_1_util_vector_logic_0_60} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_61/design_1_util_vector_logic_0_61.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_61 || ORIG_REF_NAME==design_1_util_vector_logic_0_61} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_3_0/design_1_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_3_0 || ORIG_REF_NAME==design_1_util_vector_logic_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_4_0/design_1_util_vector_logic_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_4_0 || ORIG_REF_NAME==design_1_util_vector_logic_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_5_0/design_1_util_vector_logic_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_5_0 || ORIG_REF_NAME==design_1_util_vector_logic_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SIVERS_gpio_0_0/design_1_SIVERS_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SIVERS_gpio_0_0 || ORIG_REF_NAME==design_1_SIVERS_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_3_1/design_1_util_vector_logic_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_3_1 || ORIG_REF_NAME==design_1_util_vector_logic_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_3_2/design_1_util_vector_logic_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_3_2 || ORIG_REF_NAME==design_1_util_vector_logic_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_3_3/design_1_util_vector_logic_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_3_3 || ORIG_REF_NAME==design_1_util_vector_logic_3_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_3_4/design_1_util_vector_logic_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_3_4 || ORIG_REF_NAME==design_1_util_vector_logic_3_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_62/design_1_util_vector_logic_0_62.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_62 || ORIG_REF_NAME==design_1_util_vector_logic_0_62} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_63/design_1_util_vector_logic_0_63.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_63 || ORIG_REF_NAME==design_1_util_vector_logic_0_63} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_64/design_1_util_vector_logic_0_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_64 || ORIG_REF_NAME==design_1_util_vector_logic_0_64} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_65/design_1_util_vector_logic_0_65.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_65 || ORIG_REF_NAME==design_1_util_vector_logic_0_65} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_6_0/design_1_util_vector_logic_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_6_0 || ORIG_REF_NAME==design_1_util_vector_logic_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_9_0/design_1_util_vector_logic_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_9_0 || ORIG_REF_NAME==design_1_util_vector_logic_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_9_1/design_1_util_vector_logic_9_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_9_1 || ORIG_REF_NAME==design_1_util_vector_logic_9_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_9_2/design_1_util_vector_logic_9_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_9_2 || ORIG_REF_NAME==design_1_util_vector_logic_9_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_intr_block_0_0/design_1_intr_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_intr_block_0_0 || ORIG_REF_NAME==design_1_intr_block_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_2 || ORIG_REF_NAME==design_1_auto_ds_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_3/design_1_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_3 || ORIG_REF_NAME==design_1_auto_ds_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_4/design_1_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_4 || ORIG_REF_NAME==design_1_auto_ds_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_5/design_1_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_5 || ORIG_REF_NAME==design_1_auto_ds_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
