# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_2x2+sub6Ghz_4x4/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_0_5/design_1_axis_combiner_0_5.xci
# IP: The module: 'design_1_axis_combiner_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_2x2+sub6Ghz_4x4/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_0_5/design_1_axis_combiner_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_combiner_0_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_2x2+sub6Ghz_4x4/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_0_5/design_1_axis_combiner_0_5.xci
# IP: The module: 'design_1_axis_combiner_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_2x2+sub6Ghz_4x4/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_0_5/design_1_axis_combiner_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_combiner_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
