function [RX_FRAME_CFO] = CFO_CORRECTION(RX_FRAME,CFO_EST,DEC_PARAM)

%% OWN FUNCTION
% [RX_FRAME_CFO, ~] = FREQ_OFFSET_CORR_v2(RX_FRAME,angle_est,DECODER_PARAM.CFOC.n_bits_NCO,DECODER_PARAM.SRRC.osps,INDEX2);
  
%% MATLAB FUNCTION       
RX_FRAME_CFO = helperFrequencyOffset(RX_FRAME,2*DEC_PARAM.fs,-CFO_EST);

end

