# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.enableLutRouteBelPower 1
set_param chipscope.maxJobs 4
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xczu28dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen/tlast_gen.cache/wt [current_project]
set_property parent.project_path /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen/tlast_gen.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu111:part0:1.2 [current_project]
set_property ip_repo_paths /home/rafael/Documentos/RFSoc/ip_repo/tlast [current_project]
update_ip_catalog
set_property ip_output_repo /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen/tlast_gen.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen_v1_0_S00_AXI.v
  /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen_v1_0.v
}
read_vhdl -library xil_defaultlib /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen/tlast_gen.srcs/sources_1/imports/src/vt_single_sync.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen/tlast_gen.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/rafael/Documentos/RFSoc/ip_repo/tlast/tlast_gen/tlast_gen.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top tlast_gen_v1_0 -part xczu28dr-ffvg1517-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef tlast_gen_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file tlast_gen_v1_0_utilization_synth.rpt -pb tlast_gen_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
