set_property SRC_FILE_INFO {cfile:/home/rafael/Documentos/RFSoC_Vivado/mmW_2x2+uW_4x4/Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc rfile:../../../Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/rafael/Documentos/RFSoC_Vivado/mmW_2x2+uW_4x4/Basic_1x1.srcs/constrs_1/new/timing.xdc rfile:../../../Basic_1x1.srcs/constrs_1/new/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL16 [get_ports {CLK_DIFF_PL_CLK_clk_p[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15 [get_ports {CLK_DIFF_PL_CLK_clk_n[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {CLK_DIFF_SYSREF_CLK_clk_p[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK16 [get_ports {CLK_DIFF_SYSREF_CLK_clk_n[0]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {pll1_clk}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS12 [get_ports {pll1_clk}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {sysref_clk}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS12 [get_ports {sysref_clk}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc00/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc02/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc10/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc12/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc30/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc32/mrk_cntr_ff_reg[*]/CE}]
