# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_packet_counter_0_2/design_1_packet_counter_0_2.xci
# IP: The module: 'design_1_packet_counter_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_packet_counter_0_2/src/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_packet_counter_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_packet_counter_0_2/design_1_packet_counter_0_2.xci
# IP: The module: 'design_1_packet_counter_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_packet_counter_0_2/src/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_packet_counter_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
