set_property SRC_FILE_INFO {cfile:/home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_LS/Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc rfile:../../../Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_LS/Basic_1x1.srcs/constrs_1/new/timing.xdc rfile:../../../Basic_1x1.srcs/constrs_1/new/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL16 [get_ports {CLK_DIFF_PL_CLK_clk_p[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15 [get_ports {CLK_DIFF_PL_CLK_clk_n[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {CLK_DIFF_SYSREF_CLK_clk_p[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK16 [get_ports {CLK_DIFF_SYSREF_CLK_clk_n[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP5 [get_ports {o_INC_BP_0}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP6 [get_ports {o_RST_BP_0}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR6 [get_ports {o_RTN_BP_0}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR7 [get_ports {SPI_SS0}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV7 [get_ports {SPI_SCLK0}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU7 [get_ports {SPI_MO0}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV8 [get_ports {o_INC_BP_1}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU8 [get_ports {o_RST_BP_1}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT6 [get_ports {o_RTN_BP_1}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT7 [get_ports {SPI_SS1}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU5 [get_ports {SPI_SCLK1}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT5 [get_ports {SPI_MO1}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports {o_INC_BP_2}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10 [get_ports {o_RST_BP_2}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A6 [get_ports {o_RTN_BP_2}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7 [get_ports {SPI_SS2}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {SPI_SCLK2}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {SPI_MO2}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C5 [get_ports {o_INC_BP_3}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C6 [get_ports {o_RST_BP_3}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports {o_RTN_BP_3}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports {SPI_SS3}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7 [get_ports {SPI_SCLK3}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B8 [get_ports {SPI_MO3}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU3 [get_ports {o_GND_0}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU4 [get_ports {o_GND_1}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV5 [get_ports {o_1v8_0}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV6 [get_ports {o_1v8_1}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU1 [get_ports {o_1v8_4}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU2 [get_ports {o_1v8_6}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports {o_GND_2}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D9 [get_ports {o_GND_3}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports {o_1v8_2}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C8 [get_ports {o_1v8_3}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C10 [get_ports {o_1v8_5}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports {o_1v8_7}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc00/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc02/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc10/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc12/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc20/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc22/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc30/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc32/mrk_cntr_ff_reg[*]/CE}]
