#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Oct 22 15:40:14 CEST 2021
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_5 zynq_ultra_ps_e_vip_v1_0_5 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xlconstant_v1_1_6 xlslice_v1_0_2 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_19 fifo_generator_v13_2_4 axi_data_fifo_v2_1_18 axi_crossbar_v2_1_20 util_vector_logic_v2_0_1 axi_protocol_converter_v2_1_19 axi_clock_converter_v2_1_18 blk_mem_gen_v8_4_3 axi_dwidth_converter_v2_1_19)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_block.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm_top.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_bgt_fsm.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_device_rom.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_por_fsm_disabled.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_tile_config.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_constants_config.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_arbiter.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_arbiter_adc.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_register_decode.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_address_decoder.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_axi_lite_ipif.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_counter_f.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_pselect_f.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_slave_attachment.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_rf_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_control_top.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_control.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_drp_access_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_irq_req_ack.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_irq_sync.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0bufg_gt_ctrl.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_overvol_irq.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_powerup_state_irq.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_sysref_count.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_mrk_count.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_data_align.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_mt_fifo_ctrl.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_rst_cnt.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_96M_0/sim/design_1_rst_ps8_0_96M_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_ds_buf_0_2/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_ds_buf_0_2/sim/design_1_util_ds_buf_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_96M_1/sim/design_1_rst_ps8_0_96M_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_ds_buf_0_3/sim/design_1_util_ds_buf_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ipshared/f27c/sync.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_0_4/sim/design_1_sync_0_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_0_5/sim/design_1_sync_0_5.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_3/sim/design_1_xlconstant_0_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_2/sim/design_1_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_0_12/sim/design_1_sync_0_12.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_ps8_0_96M1_0/sim/design_1_rst_ps8_0_96M1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_0_13/sim/design_1_sync_0_13.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/f044/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_globalstart_gpio_0/sim/design_1_globalstart_gpio_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ace7/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xbar_3/sim/design_1_xbar_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/c6e7/hdl/packet_detector_11AD_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c6e7/hdl/packet_detector_11AD_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c6e7/src/packet_detector_v3.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/c6e7/src/vt_single_sync.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_packet_detector_11AD_0_0/sim/design_1_packet_detector_11AD_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_packet_detector_11AD_0_1/sim/design_1_packet_detector_11AD_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_packet_detector_11AD_0_3/sim/design_1_packet_detector_11AD_0_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_packet_detector_11AD_0_2/sim/design_1_packet_detector_11AD_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_17/sim/design_1_xlslice_0_17.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_48/sim/design_1_util_vector_logic_0_48.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_50/sim/design_1_util_vector_logic_0_50.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_0_21/sim/design_1_sync_0_21.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_15/sim/design_1_xlconstant_0_15.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_19/sim/design_1_xlslice_0_19.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_52/sim/design_1_util_vector_logic_0_52.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_2_8/sim/design_1_util_vector_logic_2_8.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_1_6/sim/design_1_sync_1_6.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_17/sim/design_1_xlconstant_0_17.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_21/sim/design_1_xlslice_0_21.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_54/sim/design_1_util_vector_logic_0_54.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_2_10/sim/design_1_util_vector_logic_2_10.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_1_8/sim/design_1_sync_1_8.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_19/sim/design_1_xlconstant_0_19.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_20/sim/design_1_xlslice_0_20.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_53/sim/design_1_util_vector_logic_0_53.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_2_9/sim/design_1_util_vector_logic_2_9.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_1_7/sim/design_1_sync_1_7.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_18/sim/design_1_xlconstant_0_18.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_globalstart_gpio_adc_0/sim/design_1_globalstart_gpio_adc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_1_9/sim/design_1_sync_1_9.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/da5c/hdl/SHAPING_FILTER.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/da5c/hdl/TX_BLOCK_STA.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/da5c/hdl/TX_Block_STA_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/da5c/hdl/TX_Block_STA_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_TX_Block_STA_0_5/sim/design_1_TX_Block_STA_0_5.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_TX_Block_STA_0_3/sim/design_1_TX_Block_STA_0_3.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_TX_Block_STA_0_4/sim/design_1_TX_Block_STA_0_4.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_TX_Block_STA_0_2/sim/design_1_TX_Block_STA_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlslice_0_22/sim/design_1_xlslice_0_22.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_55/sim/design_1_util_vector_logic_0_55.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_2_11/sim/design_1_util_vector_logic_2_11.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_sync_1_10/sim/design_1_sync_1_10.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_xlconstant_0_20/sim/design_1_xlconstant_0_20.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/sim/ila_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/fifo_generator_0/sim/fifo_generator_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/FIFO_BD_CIR_v3/sim/FIFO_BD_CIR_v3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/Boundary_Detector_v1.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/CIR_BLOCK.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/FIFO_BD_CIR_TOP_v3.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/GOLAY_CORR_v1.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/GOLAY_CU.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/RX_block_STA_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/RX_block_STA_v1_0_S01_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/STA_RX_BLOCK_TOP.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/ifr1max6i.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/ifr1max_r2i.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/f73f/src/RX_block_STA_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/sim/design_1_RX_Block_STA_v2_0_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/sim/design_1_RX_Block_STA_v2_0_1.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/sim/design_1_RX_Block_STA_v2_0_2.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/sim/design_1_RX_Block_STA_v2_0_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_56/sim/design_1_util_vector_logic_0_56.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_57/sim/design_1_util_vector_logic_0_57.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_58/sim/design_1_util_vector_logic_0_58.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_59/sim/design_1_util_vector_logic_0_59.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_60/sim/design_1_util_vector_logic_0_60.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_61/sim/design_1_util_vector_logic_0_61.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_3_0/sim/design_1_util_vector_logic_3_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_4_0/sim/design_1_util_vector_logic_4_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_5_0/sim/design_1_util_vector_logic_5_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ipshared/74b9/src/SIVERS_GPIO_CHANGE_v2.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/74b9/hdl/SIVERS_gpio_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/design_1/ipshared/74b9/hdl/SIVERS_gpio_v1_0.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_SIVERS_gpio_0_0/sim/design_1_SIVERS_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_3_1/sim/design_1_util_vector_logic_3_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_3_2/sim/design_1_util_vector_logic_3_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_3_3/sim/design_1_util_vector_logic_3_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_3_4/sim/design_1_util_vector_logic_3_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_62/sim/design_1_util_vector_logic_0_62.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_63/sim/design_1_util_vector_logic_0_63.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_64/sim/design_1_util_vector_logic_0_64.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_0_65/sim/design_1_util_vector_logic_0_65.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_6_0/sim/design_1_util_vector_logic_6_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_9_0/sim/design_1_util_vector_logic_9_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_9_1/sim/design_1_util_vector_logic_9_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_util_vector_logic_9_2/sim/design_1_util_vector_logic_9_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_intr_block_0_0/sim/design_1_intr_block_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_0_0/sim/design_1_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_1_0/sim/design_1_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_tier2_xbar_2_0/sim/design_1_tier2_xbar_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ac9d/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c001/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/e578/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/cac7/hdl" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ipshared/c923" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_0/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_1/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_2/src/ila_0/hdl/verilog" +incdir+"$ref_dir/../../../../Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_STA_v2_0_3/src/ila_0/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_2/sim/design_1_auto_ds_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_2/sim/design_1_auto_pc_2.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_3/sim/design_1_auto_ds_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_3/sim/design_1_auto_pc_3.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_4/sim/design_1_auto_ds_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_4/sim/design_1_auto_pc_4.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_5/sim/design_1_auto_ds_5.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_5/sim/design_1_auto_pc_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/sim/design_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
