# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
create_project -in_memory -part xczu28dr-ffvg1517-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.cache/wt [current_project]
set_property parent.project_path /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zcu111:part0:1.2 [current_project]
set_property ip_repo_paths {
  /home/rafael/Documentos/RFSoc/ip_repo/rate_converter_1.0
  /home/rafael/Documentos/RFSoc/ip_repo/packet_detector_11AD_1.0
  /home/rafael/Documentos/RFSoc/ip_repo/rate_conversion_1.0
  /home/rafael/Documentos/RFSoc/ip_repo/ddr_writer_1.0
  /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/srcs/ip/ip_repo
  /home/rafael/Documentos/RFSoc/ip_source
  /home/rafael/Documentos/RFSoc/ip_repo/rate_converter_5b_1.0
  /home/rafael/Documentos/RFSoc/ip_repo/tlast
  /home/rafael/Documentos/RFSoc/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/synth/design_1_usp_rf_data_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_1/design_1_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_2/design_1_axis_data_fifo_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/design_1_ddr4_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/par/design_1_ddr4_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_0/design_1_ddr4_0_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_0/design_1_ddr4_0_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_0/bd_45eb_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_0/bd_45eb_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_1/bd_45eb_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_1/bd_45eb_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_2/bd_45eb_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_3/bd_45eb_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_6/bd_45eb_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_9/bd_45eb_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_10/bd_45eb_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/bd_45eb_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/par/design_1_ddr4_0_0_phy_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_333M_1/design_1_rst_ddr4_0_333M_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_333M_1/design_1_rst_ddr4_0_333M_1.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ddr4_0_333M_1/design_1_rst_ddr4_0_333M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_3/design_1_util_ds_buf_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_3/design_1_util_ds_buf_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_2/design_1_axis_broadcaster_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_3/design_1_axis_data_fifo_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_0/design_1_axis_data_fifo_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_0/design_1_axis_data_fifo_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_1/design_1_axis_register_slice_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_1/design_1_axis_register_slice_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_1/design_1_axis_broadcaster_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_4/design_1_axis_data_fifo_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_1/design_1_axis_data_fifo_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_3/design_1_axis_data_fifo_2_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_4/design_1_axis_register_slice_0_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_4/design_1_axis_register_slice_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_3/design_1_axis_broadcaster_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_5/design_1_axis_data_fifo_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_2/design_1_axis_data_fifo_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_4/design_1_axis_data_fifo_2_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_5/design_1_axis_register_slice_0_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_5/design_1_axis_register_slice_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_4/design_1_axis_broadcaster_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_6/design_1_axis_data_fifo_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_0_1/design_1_axis_combiner_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_writer_impl.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_ddr_writer_v1_0.srcs/sources_1/ip/DDR_WRITER_FIFO/DDR_WRITER_FIFO.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_ddr_writer_v1_0.srcs/sources_1/ip/DDR_WRITER_FIFO/DDR_WRITER_FIFO_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_ddr_writer_v1_0.srcs/sources_1/ip/ila_0_3/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_ddr_writer_v1_0.srcs/sources_1/ip/ila_0_3/ila_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_0/design_1_axi_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_0/design_1_axi_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_2/design_1_axi_register_slice_0_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_2/design_1_axi_register_slice_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_8/design_1_axis_register_slice_0_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_8/design_1_axis_register_slice_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_1_0/design_1_axi_register_slice_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_1_0/design_1_axi_register_slice_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_3/design_1_axi_register_slice_0_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axi_register_slice_0_3/design_1_axi_register_slice_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_14/design_1_axis_register_slice_0_14_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_14/design_1_axis_register_slice_0_14_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_15/design_1_axis_register_slice_0_15_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_15/design_1_axis_register_slice_0_15_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_16/design_1_axis_register_slice_0_16_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_16/design_1_axis_register_slice_0_16_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_7/design_1_axis_data_fifo_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_4/design_1_axis_data_fifo_1_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_5/design_1_axis_data_fifo_2_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_17/design_1_axis_register_slice_0_17_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_17/design_1_axis_register_slice_0_17_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_5/design_1_axis_broadcaster_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_8/design_1_axis_data_fifo_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_5/design_1_axis_data_fifo_1_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_6/design_1_axis_data_fifo_2_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_18/design_1_axis_register_slice_0_18_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_18/design_1_axis_register_slice_0_18_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_6/design_1_axis_broadcaster_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_9/design_1_axis_data_fifo_0_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_6/design_1_axis_data_fifo_1_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_7/design_1_axis_data_fifo_2_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_19/design_1_axis_register_slice_0_19_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_19/design_1_axis_register_slice_0_19_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_7/design_1_axis_broadcaster_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_10/design_1_axis_data_fifo_0_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_7/design_1_axis_data_fifo_1_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_2_8/design_1_axis_data_fifo_2_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_20/design_1_axis_register_slice_0_20_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_20/design_1_axis_register_slice_0_20_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_broadcaster_0_8/design_1_axis_broadcaster_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_1_2/design_1_axis_register_slice_1_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_1_2/design_1_axis_register_slice_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_1_3/design_1_axis_register_slice_1_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_1_3/design_1_axis_register_slice_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tlast_gen_v1_0_0_8/tlast_gen/tlast_gen.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_0/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_1/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_2/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_3/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_5/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_7/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_4/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_idle_packet_0_6/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_SIVERS_gpio_0_0/src/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_0_5/design_1_axis_dwidth_converter_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_0_6/design_1_axis_dwidth_converter_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_1_3/design_1_axis_dwidth_converter_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_2_0/design_1_axis_dwidth_converter_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_3_0/design_1_axis_dwidth_converter_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_3_1/design_1_axis_dwidth_converter_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_3_2/design_1_axis_dwidth_converter_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_dwidth_converter_3_3/design_1_axis_dwidth_converter_3_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_3_0/design_1_axis_combiner_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_1_0/design_1_axis_combiner_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_combiner_0_4/design_1_axis_combiner_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tlast_gen_v1_0_3_0/tlast_gen/tlast_gen.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_3_0/design_1_axis_data_fifo_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_13/design_1_axis_data_fifo_0_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tlast_gen_v1_0_0_9/tlast_gen/tlast_gen.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tlast_gen_v1_0_1_0/tlast_gen/tlast_gen.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_1_10/design_1_axis_data_fifo_1_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_24/design_1_axis_register_slice_0_24_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_24/design_1_axis_register_slice_0_24_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_26/design_1_axis_register_slice_0_26_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_26/design_1_axis_register_slice_0_26_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_27/design_1_axis_register_slice_0_27_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_27/design_1_axis_register_slice_0_27_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_28/design_1_axis_register_slice_0_28_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_28/design_1_axis_register_slice_0_28_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_29/design_1_axis_register_slice_0_29_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_29/design_1_axis_register_slice_0_29_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_30/design_1_axis_register_slice_0_30_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_30/design_1_axis_register_slice_0_30_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_25/design_1_axis_register_slice_0_25_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_25/design_1_axis_register_slice_0_25_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_reg_and_mux_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_reg_and_mux_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_reg_and_mux_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/constrs_1/new/constraints.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_bit_slicer_v1_0.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_sample_concatenation_v1_0.srcs/sources_1/ip/ila_reg_and_mux/ila_reg_and_mux_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_usp_rf_data_converter_0_0/data/startup.elf]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/sw/calibration_0/Debug/calibration_ddr.elf]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc
set_property used_in_implementation false [get_files /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc]

read_xdc /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/constrs_1/new/timing.xdc
set_property used_in_implementation false [get_files /home/rafael/Documentos/RFSoc/MTS_4x4_5b_nw/Basic_1x1.srcs/constrs_1/new/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xczu28dr-ffvg1517-2-e -flatten_hierarchy none -keep_equivalent_registers


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
