# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_TX_Block_STA_0_5/design_1_TX_Block_STA_0_5.xci
# IP: The module: 'design_1_TX_Block_STA_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/TX_Block_STA_v1_0/TX_Block_STA_v1_0.srcs/constrs_1/new/constrains.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_TX_Block_STA_0_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_TX_Block_STA_0_5/design_1_TX_Block_STA_0_5.xci
# IP: The module: 'design_1_TX_Block_STA_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_STA/Basic_1x1.srcs/sources_1/bd/design_1/ip/TX_Block_STA_v1_0/TX_Block_STA_v1_0.srcs/constrs_1/new/constrains.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_TX_Block_STA_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
