# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_AP_0_2/design_1_RX_Block_AP_0_2.xci
# IP: The module: 'design_1_RX_Block_AP_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_Block_AP_v1_0_project/RX_Block_AP_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_BD_CIR_v3 || ORIG_REF_NAME==FIFO_BD_CIR_v3} -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_Block_AP_v1_0_project/RX_Block_AP_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_BD_CIR_v3 || ORIG_REF_NAME==FIFO_BD_CIR_v3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_Block_AP_v1_0_project/RX_Block_AP_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_BD_CIR_v3 || ORIG_REF_NAME==FIFO_BD_CIR_v3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_AP_0_2/src/contraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RX_Block_AP_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_AP_0_2/design_1_RX_Block_AP_0_2.xci
# IP: The module: 'design_1_RX_Block_AP_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_Block_AP_v1_0_project/RX_Block_AP_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_BD_CIR_v3 || ORIG_REF_NAME==FIFO_BD_CIR_v3} -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_Block_AP_v1_0_project/RX_Block_AP_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_BD_CIR_v3 || ORIG_REF_NAME==FIFO_BD_CIR_v3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/RX_Block_AP_v1_0_project/RX_Block_AP_v1_0_project.srcs/sources_1/ip/FIFO_BD_CIR_v3/FIFO_BD_CIR_v3_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_BD_CIR_v3 || ORIG_REF_NAME==FIFO_BD_CIR_v3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_RX_Block_AP_0_2/src/contraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RX_Block_AP_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
