# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/design_1_ddr_writer_0_7.xci
# IP: The module: 'design_1_ddr_writer_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_WRITER_FIFO/DDR_WRITER_FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_WRITER_FIFO || ORIG_REF_NAME==DDR_WRITER_FIFO} -quiet] -quiet

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_WRITER_FIFO/DDR_WRITER_FIFO.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_WRITER_FIFO || ORIG_REF_NAME==DDR_WRITER_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_WRITER_FIFO/DDR_WRITER_FIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_WRITER_FIFO || ORIG_REF_NAME==DDR_WRITER_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_writer_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ddr_writer_0_7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/design_1_ddr_writer_0_7.xci
# IP: The module: 'design_1_ddr_writer_0_7' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_WRITER_FIFO/DDR_WRITER_FIFO.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DDR_WRITER_FIFO || ORIG_REF_NAME==DDR_WRITER_FIFO} -quiet] -quiet

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_WRITER_FIFO/DDR_WRITER_FIFO.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_WRITER_FIFO || ORIG_REF_NAME==DDR_WRITER_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_WRITER_FIFO/DDR_WRITER_FIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DDR_WRITER_FIFO || ORIG_REF_NAME==DDR_WRITER_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_PD/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_ddr_writer_0_7/src/DDR_writer_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ddr_writer_0_7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
