set_property SRC_FILE_INFO {cfile:/home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_nw/Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc rfile:../../../Basic_1x1.srcs/constrs_1/new/placing_constraints.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_nw/Basic_1x1.srcs/constrs_1/new/timing.xdc rfile:../../../Basic_1x1.srcs/constrs_1/new/timing.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL16 [get_ports {CLK_DIFF_PL_CLK_clk_p[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15 [get_ports {CLK_DIFF_PL_CLK_clk_n[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {CLK_DIFF_SYSREF_CLK_clk_p[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK16 [get_ports {CLK_DIFF_SYSREF_CLK_clk_n[0]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {o_INC_BP_0}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {o_RST_BP_0}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {o_RTN_BP_0}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {o_INC_BP_1}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {o_RST_BP_1}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports {o_RTN_BP_1}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports {o_INC_BP_2}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports {o_RST_BP_2}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {o_RTN_BP_2}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {o_INC_BP_3}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports {o_RST_BP_3}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {o_RTN_BP_3}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc00/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc02/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc10/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc12/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc20/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc22/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc30/mrk_cntr_ff_reg[*]/CE}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins {design_1_i/MTS_Block/sync_2/inst/xpm_cdc_single_inst/syncstages_ff_reg[*]/C}] -to [get_pins {design_1_i/usp_rf_data_converter_0/inst/i_rf_conv_mt_mrk_counter_adc32/mrk_cntr_ff_reg[*]/CE}]
