# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_5b/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_sample_concatenation_2_0/design_1_sample_concatenation_2_0.xci
# IP: The module: 'design_1_sample_concatenation_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_5b/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_sample_concatenation_2_0/src/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dwidth_converter_0 || ORIG_REF_NAME==axis_dwidth_converter_0} -quiet] -quiet

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_5b/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_sample_concatenation_2_0/design_1_sample_concatenation_2_0.xci
# IP: The module: 'design_1_sample_concatenation_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documents/MIMORPH/MIMORPH/MIMO_mm-wave_4x4_5b/HW/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_sample_concatenation_2_0/src/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_dwidth_converter_0 || ORIG_REF_NAME==axis_dwidth_converter_0} -quiet] -quiet
