# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/placing_constraints.xdc

# XDC: new/timing.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_usp_rf_data_converter_0_0/design_1_usp_rf_data_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_usp_rf_data_converter_0_0 || ORIG_REF_NAME==design_1_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M_0/design_1_rst_ps8_0_96M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_2/design_1_util_ds_buf_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_2 || ORIG_REF_NAME==design_1_util_ds_buf_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M_1/design_1_rst_ps8_0_96M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M_1 || ORIG_REF_NAME==design_1_rst_ps8_0_96M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_1/design_1_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_1 || ORIG_REF_NAME==design_1_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_2/design_1_axis_data_fifo_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_2 || ORIG_REF_NAME==design_1_axis_data_fifo_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_0/design_1_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_0 || ORIG_REF_NAME==design_1_axis_register_slice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_0 || ORIG_REF_NAME==design_1_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_0/design_1_adc_strm_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_0 || ORIG_REF_NAME==design_1_adc_strm_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_0/design_1_sync_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_0 || ORIG_REF_NAME==design_1_sync_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_1/design_1_sync_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_1 || ORIG_REF_NAME==design_1_sync_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_0/design_1_util_vector_logic_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_0 || ORIG_REF_NAME==design_1_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ddr4_0_0/design_1_ddr4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ddr4_0_0 || ORIG_REF_NAME==design_1_ddr4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ddr4_0_333M_1/design_1_rst_ddr4_0_333M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ddr4_0_333M_1 || ORIG_REF_NAME==design_1_rst_ddr4_0_333M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_ds_buf_0_3/design_1_util_ds_buf_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_0_3 || ORIG_REF_NAME==design_1_util_ds_buf_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_4/design_1_sync_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_4 || ORIG_REF_NAME==design_1_sync_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_5/design_1_sync_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_5 || ORIG_REF_NAME==design_1_sync_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_3/design_1_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_3 || ORIG_REF_NAME==design_1_xlconstant_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_6/design_1_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_6 || ORIG_REF_NAME==design_1_xlslice_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_3/design_1_sync_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_3 || ORIG_REF_NAME==design_1_sync_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_2/design_1_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_2 || ORIG_REF_NAME==design_1_xlconstant_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_7/design_1_util_vector_logic_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_7 || ORIG_REF_NAME==design_1_util_vector_logic_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_8/design_1_util_vector_logic_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_8 || ORIG_REF_NAME==design_1_util_vector_logic_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_2/design_1_axis_broadcaster_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_2 || ORIG_REF_NAME==design_1_axis_broadcaster_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_3/design_1_axis_data_fifo_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_3 || ORIG_REF_NAME==design_1_axis_data_fifo_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_0/design_1_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_0 || ORIG_REF_NAME==design_1_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_0/design_1_axis_data_fifo_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_0 || ORIG_REF_NAME==design_1_axis_data_fifo_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_1/design_1_adc_strm_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_1 || ORIG_REF_NAME==design_1_adc_strm_mux_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_9/design_1_util_vector_logic_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_9 || ORIG_REF_NAME==design_1_util_vector_logic_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_0 || ORIG_REF_NAME==design_1_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_1/design_1_axis_register_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_1 || ORIG_REF_NAME==design_1_axis_register_slice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_7/design_1_xlslice_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_7 || ORIG_REF_NAME==design_1_xlslice_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_6/design_1_sync_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_6 || ORIG_REF_NAME==design_1_sync_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_0/design_1_sync_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_0 || ORIG_REF_NAME==design_1_sync_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_4/design_1_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_4 || ORIG_REF_NAME==design_1_xlconstant_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_1/design_1_util_vector_logic_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_1 || ORIG_REF_NAME==design_1_util_vector_logic_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_10/design_1_util_vector_logic_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_10 || ORIG_REF_NAME==design_1_util_vector_logic_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_1/design_1_util_vector_logic_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_1 || ORIG_REF_NAME==design_1_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_1/design_1_axis_broadcaster_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_1 || ORIG_REF_NAME==design_1_axis_broadcaster_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_8/design_1_xlslice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_8 || ORIG_REF_NAME==design_1_xlslice_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_12/design_1_util_vector_logic_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_12 || ORIG_REF_NAME==design_1_util_vector_logic_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_2/design_1_util_vector_logic_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_2 || ORIG_REF_NAME==design_1_util_vector_logic_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_3/design_1_util_vector_logic_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_3 || ORIG_REF_NAME==design_1_util_vector_logic_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_5/design_1_util_vector_logic_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_5 || ORIG_REF_NAME==design_1_util_vector_logic_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_localstart_gpio_1/design_1_localstart_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_localstart_gpio_1 || ORIG_REF_NAME==design_1_localstart_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_7/design_1_sync_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_7 || ORIG_REF_NAME==design_1_sync_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_5/design_1_xlconstant_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_5 || ORIG_REF_NAME==design_1_xlconstant_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_8/design_1_sync_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_8 || ORIG_REF_NAME==design_1_sync_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_6/design_1_xlconstant_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_6 || ORIG_REF_NAME==design_1_xlconstant_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_12/design_1_sync_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_12 || ORIG_REF_NAME==design_1_sync_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_96M1_0/design_1_rst_ps8_0_96M1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_96M1_0 || ORIG_REF_NAME==design_1_rst_ps8_0_96M1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_13/design_1_sync_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_13 || ORIG_REF_NAME==design_1_sync_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_globalstart_gpio_0/design_1_globalstart_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_globalstart_gpio_0 || ORIG_REF_NAME==design_1_globalstart_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_4/design_1_axis_data_fifo_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_4 || ORIG_REF_NAME==design_1_axis_data_fifo_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_1/design_1_axis_data_fifo_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_1 || ORIG_REF_NAME==design_1_axis_data_fifo_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_3/design_1_axis_data_fifo_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_3 || ORIG_REF_NAME==design_1_axis_data_fifo_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_2/design_1_adc_strm_mux_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_2 || ORIG_REF_NAME==design_1_adc_strm_mux_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_4/design_1_axis_register_slice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_4 || ORIG_REF_NAME==design_1_axis_register_slice_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_10/design_1_xlslice_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_10 || ORIG_REF_NAME==design_1_xlslice_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_14/design_1_sync_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_14 || ORIG_REF_NAME==design_1_sync_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_2/design_1_sync_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_2 || ORIG_REF_NAME==design_1_sync_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_8/design_1_xlconstant_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_8 || ORIG_REF_NAME==design_1_xlconstant_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_3/design_1_util_vector_logic_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_3 || ORIG_REF_NAME==design_1_util_vector_logic_2_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_16/design_1_util_vector_logic_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_16 || ORIG_REF_NAME==design_1_util_vector_logic_0_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_9/design_1_util_vector_logic_1_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_9 || ORIG_REF_NAME==design_1_util_vector_logic_1_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_3/design_1_axis_broadcaster_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_3 || ORIG_REF_NAME==design_1_axis_broadcaster_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_loopback_gpio_0/design_1_loopback_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_loopback_gpio_0 || ORIG_REF_NAME==design_1_loopback_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_17/design_1_util_vector_logic_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_17 || ORIG_REF_NAME==design_1_util_vector_logic_0_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_10/design_1_util_vector_logic_1_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_10 || ORIG_REF_NAME==design_1_util_vector_logic_1_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_11/design_1_util_vector_logic_1_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_11 || ORIG_REF_NAME==design_1_util_vector_logic_1_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_localstart_gpio_2/design_1_localstart_gpio_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_localstart_gpio_2 || ORIG_REF_NAME==design_1_localstart_gpio_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_15/design_1_sync_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_15 || ORIG_REF_NAME==design_1_sync_0_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_9/design_1_xlconstant_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_9 || ORIG_REF_NAME==design_1_xlconstant_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_5/design_1_axis_data_fifo_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_5 || ORIG_REF_NAME==design_1_axis_data_fifo_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_2/design_1_axis_data_fifo_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_2 || ORIG_REF_NAME==design_1_axis_data_fifo_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_4/design_1_axis_data_fifo_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_4 || ORIG_REF_NAME==design_1_axis_data_fifo_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_3/design_1_adc_strm_mux_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_3 || ORIG_REF_NAME==design_1_adc_strm_mux_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_18/design_1_util_vector_logic_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_18 || ORIG_REF_NAME==design_1_util_vector_logic_0_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_12/design_1_util_vector_logic_1_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_12 || ORIG_REF_NAME==design_1_util_vector_logic_1_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_5/design_1_axis_register_slice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_5 || ORIG_REF_NAME==design_1_axis_register_slice_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_11/design_1_xlslice_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_11 || ORIG_REF_NAME==design_1_xlslice_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_16/design_1_sync_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_16 || ORIG_REF_NAME==design_1_sync_0_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_3/design_1_sync_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_3 || ORIG_REF_NAME==design_1_sync_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_10/design_1_xlconstant_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_10 || ORIG_REF_NAME==design_1_xlconstant_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_4/design_1_util_vector_logic_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_4 || ORIG_REF_NAME==design_1_util_vector_logic_2_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_19/design_1_util_vector_logic_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_19 || ORIG_REF_NAME==design_1_util_vector_logic_0_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_13/design_1_util_vector_logic_1_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_13 || ORIG_REF_NAME==design_1_util_vector_logic_1_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_4/design_1_axis_broadcaster_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_4 || ORIG_REF_NAME==design_1_axis_broadcaster_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_12/design_1_xlslice_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_12 || ORIG_REF_NAME==design_1_xlslice_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_14/design_1_util_vector_logic_1_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_14 || ORIG_REF_NAME==design_1_util_vector_logic_1_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_localstart_gpio_3/design_1_localstart_gpio_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_localstart_gpio_3 || ORIG_REF_NAME==design_1_localstart_gpio_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_17/design_1_sync_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_17 || ORIG_REF_NAME==design_1_sync_0_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_11/design_1_xlconstant_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_11 || ORIG_REF_NAME==design_1_xlconstant_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_6/design_1_axis_data_fifo_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_6 || ORIG_REF_NAME==design_1_axis_data_fifo_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_13/design_1_xlslice_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_13 || ORIG_REF_NAME==design_1_xlslice_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_18/design_1_sync_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_18 || ORIG_REF_NAME==design_1_sync_0_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_4/design_1_sync_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_4 || ORIG_REF_NAME==design_1_sync_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_12/design_1_xlconstant_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_12 || ORIG_REF_NAME==design_1_xlconstant_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_5/design_1_util_vector_logic_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_5 || ORIG_REF_NAME==design_1_util_vector_logic_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_20/design_1_util_vector_logic_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_20 || ORIG_REF_NAME==design_1_util_vector_logic_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_15/design_1_util_vector_logic_1_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_15 || ORIG_REF_NAME==design_1_util_vector_logic_1_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_combiner_0_1/design_1_axis_combiner_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_combiner_0_1 || ORIG_REF_NAME==design_1_axis_combiner_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_channel_mux_0_0/design_1_adc_channel_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_channel_mux_0_0 || ORIG_REF_NAME==design_1_adc_channel_mux_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_14/design_1_xlslice_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_14 || ORIG_REF_NAME==design_1_xlslice_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_16/design_1_xlslice_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_16 || ORIG_REF_NAME==design_1_xlslice_0_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_19/design_1_sync_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_19 || ORIG_REF_NAME==design_1_sync_0_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_13/design_1_xlconstant_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_13 || ORIG_REF_NAME==design_1_xlconstant_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_6/design_1_util_vector_logic_2_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_6 || ORIG_REF_NAME==design_1_util_vector_logic_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_23/design_1_util_vector_logic_0_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_23 || ORIG_REF_NAME==design_1_util_vector_logic_0_23} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_2_0/design_1_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_2_0 || ORIG_REF_NAME==design_1_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_14/design_1_xlconstant_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_14 || ORIG_REF_NAME==design_1_xlconstant_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ddr_writer_0_7/design_1_ddr_writer_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ddr_writer_0_7 || ORIG_REF_NAME==design_1_ddr_writer_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_26/design_1_util_vector_logic_0_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_26 || ORIG_REF_NAME==design_1_util_vector_logic_0_26} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_22/design_1_util_vector_logic_1_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_22 || ORIG_REF_NAME==design_1_util_vector_logic_1_22} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_0_0/design_1_axi_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_0 || ORIG_REF_NAME==design_1_axi_register_slice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_0_1/design_1_axi_register_slice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_1 || ORIG_REF_NAME==design_1_axi_register_slice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_0_2/design_1_axi_register_slice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_2 || ORIG_REF_NAME==design_1_axi_register_slice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_8/design_1_axis_register_slice_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_8 || ORIG_REF_NAME==design_1_axis_register_slice_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_1_0/design_1_axi_register_slice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_1_0 || ORIG_REF_NAME==design_1_axi_register_slice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_register_slice_0_3/design_1_axi_register_slice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_register_slice_0_3 || ORIG_REF_NAME==design_1_axi_register_slice_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_14/design_1_axis_register_slice_0_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_14 || ORIG_REF_NAME==design_1_axis_register_slice_0_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_15/design_1_axis_register_slice_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_15 || ORIG_REF_NAME==design_1_axis_register_slice_0_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_16/design_1_axis_register_slice_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_16 || ORIG_REF_NAME==design_1_axis_register_slice_0_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_7/design_1_axis_data_fifo_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_7 || ORIG_REF_NAME==design_1_axis_data_fifo_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_4/design_1_axis_data_fifo_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_4 || ORIG_REF_NAME==design_1_axis_data_fifo_1_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_5/design_1_axis_data_fifo_2_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_5 || ORIG_REF_NAME==design_1_axis_data_fifo_2_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_4/design_1_adc_strm_mux_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_4 || ORIG_REF_NAME==design_1_adc_strm_mux_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_17/design_1_axis_register_slice_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_17 || ORIG_REF_NAME==design_1_axis_register_slice_0_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_17/design_1_xlslice_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_17 || ORIG_REF_NAME==design_1_xlslice_0_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_20/design_1_sync_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_20 || ORIG_REF_NAME==design_1_sync_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_5/design_1_sync_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_5 || ORIG_REF_NAME==design_1_sync_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_15/design_1_xlconstant_0_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_15 || ORIG_REF_NAME==design_1_xlconstant_0_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_7/design_1_util_vector_logic_2_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_7 || ORIG_REF_NAME==design_1_util_vector_logic_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_28/design_1_util_vector_logic_0_28.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_28 || ORIG_REF_NAME==design_1_util_vector_logic_0_28} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_24/design_1_util_vector_logic_1_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_24 || ORIG_REF_NAME==design_1_util_vector_logic_1_24} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_5/design_1_axis_broadcaster_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_5 || ORIG_REF_NAME==design_1_axis_broadcaster_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_loopback_gpio_1/design_1_loopback_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_loopback_gpio_1 || ORIG_REF_NAME==design_1_loopback_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_29/design_1_util_vector_logic_0_29.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_29 || ORIG_REF_NAME==design_1_util_vector_logic_0_29} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_25/design_1_util_vector_logic_1_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_25 || ORIG_REF_NAME==design_1_util_vector_logic_1_25} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_26/design_1_util_vector_logic_1_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_26 || ORIG_REF_NAME==design_1_util_vector_logic_1_26} -quiet] -quiet

# IP: bd/design_1/ip/design_1_localstart_gpio_4/design_1_localstart_gpio_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_localstart_gpio_4 || ORIG_REF_NAME==design_1_localstart_gpio_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_21/design_1_sync_0_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_21 || ORIG_REF_NAME==design_1_sync_0_21} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_16/design_1_xlconstant_0_16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_16 || ORIG_REF_NAME==design_1_xlconstant_0_16} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_8/design_1_axis_data_fifo_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_8 || ORIG_REF_NAME==design_1_axis_data_fifo_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_5/design_1_axis_data_fifo_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_5 || ORIG_REF_NAME==design_1_axis_data_fifo_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_6/design_1_axis_data_fifo_2_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_6 || ORIG_REF_NAME==design_1_axis_data_fifo_2_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_5/design_1_adc_strm_mux_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_5 || ORIG_REF_NAME==design_1_adc_strm_mux_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_18/design_1_axis_register_slice_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_18 || ORIG_REF_NAME==design_1_axis_register_slice_0_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_18/design_1_xlslice_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_18 || ORIG_REF_NAME==design_1_xlslice_0_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_22/design_1_sync_0_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_22 || ORIG_REF_NAME==design_1_sync_0_22} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_6/design_1_sync_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_6 || ORIG_REF_NAME==design_1_sync_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_17/design_1_xlconstant_0_17.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_17 || ORIG_REF_NAME==design_1_xlconstant_0_17} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_8/design_1_util_vector_logic_2_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_8 || ORIG_REF_NAME==design_1_util_vector_logic_2_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_30/design_1_util_vector_logic_0_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_30 || ORIG_REF_NAME==design_1_util_vector_logic_0_30} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_27/design_1_util_vector_logic_1_27.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_27 || ORIG_REF_NAME==design_1_util_vector_logic_1_27} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_6/design_1_axis_broadcaster_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_6 || ORIG_REF_NAME==design_1_axis_broadcaster_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_loopback_gpio_2/design_1_loopback_gpio_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_loopback_gpio_2 || ORIG_REF_NAME==design_1_loopback_gpio_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_31/design_1_util_vector_logic_0_31.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_31 || ORIG_REF_NAME==design_1_util_vector_logic_0_31} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_28/design_1_util_vector_logic_1_28.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_28 || ORIG_REF_NAME==design_1_util_vector_logic_1_28} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_29/design_1_util_vector_logic_1_29.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_29 || ORIG_REF_NAME==design_1_util_vector_logic_1_29} -quiet] -quiet

# IP: bd/design_1/ip/design_1_localstart_gpio_5/design_1_localstart_gpio_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_localstart_gpio_5 || ORIG_REF_NAME==design_1_localstart_gpio_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_23/design_1_sync_0_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_23 || ORIG_REF_NAME==design_1_sync_0_23} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_18/design_1_xlconstant_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_18 || ORIG_REF_NAME==design_1_xlconstant_0_18} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_9/design_1_axis_data_fifo_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_9 || ORIG_REF_NAME==design_1_axis_data_fifo_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_6/design_1_axis_data_fifo_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_6 || ORIG_REF_NAME==design_1_axis_data_fifo_1_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_7/design_1_axis_data_fifo_2_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_7 || ORIG_REF_NAME==design_1_axis_data_fifo_2_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_6/design_1_adc_strm_mux_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_6 || ORIG_REF_NAME==design_1_adc_strm_mux_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_19/design_1_axis_register_slice_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_19 || ORIG_REF_NAME==design_1_axis_register_slice_0_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_19/design_1_xlslice_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_19 || ORIG_REF_NAME==design_1_xlslice_0_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_24/design_1_sync_0_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_24 || ORIG_REF_NAME==design_1_sync_0_24} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_7/design_1_sync_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_7 || ORIG_REF_NAME==design_1_sync_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_19/design_1_xlconstant_0_19.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_19 || ORIG_REF_NAME==design_1_xlconstant_0_19} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_9/design_1_util_vector_logic_2_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_9 || ORIG_REF_NAME==design_1_util_vector_logic_2_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_32/design_1_util_vector_logic_0_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_32 || ORIG_REF_NAME==design_1_util_vector_logic_0_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_30/design_1_util_vector_logic_1_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_30 || ORIG_REF_NAME==design_1_util_vector_logic_1_30} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_7/design_1_axis_broadcaster_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_7 || ORIG_REF_NAME==design_1_axis_broadcaster_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_loopback_gpio_3/design_1_loopback_gpio_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_loopback_gpio_3 || ORIG_REF_NAME==design_1_loopback_gpio_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_33/design_1_util_vector_logic_0_33.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_33 || ORIG_REF_NAME==design_1_util_vector_logic_0_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_31/design_1_util_vector_logic_1_31.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_31 || ORIG_REF_NAME==design_1_util_vector_logic_1_31} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_32/design_1_util_vector_logic_1_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_32 || ORIG_REF_NAME==design_1_util_vector_logic_1_32} -quiet] -quiet

# IP: bd/design_1/ip/design_1_localstart_gpio_6/design_1_localstart_gpio_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_localstart_gpio_6 || ORIG_REF_NAME==design_1_localstart_gpio_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_25/design_1_sync_0_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_25 || ORIG_REF_NAME==design_1_sync_0_25} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_20/design_1_xlconstant_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_20 || ORIG_REF_NAME==design_1_xlconstant_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_10/design_1_axis_data_fifo_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_10 || ORIG_REF_NAME==design_1_axis_data_fifo_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_7/design_1_axis_data_fifo_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_7 || ORIG_REF_NAME==design_1_axis_data_fifo_1_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_8/design_1_axis_data_fifo_2_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_8 || ORIG_REF_NAME==design_1_axis_data_fifo_2_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_strm_mux_0_7/design_1_adc_strm_mux_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adc_strm_mux_0_7 || ORIG_REF_NAME==design_1_adc_strm_mux_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_20/design_1_axis_register_slice_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_20 || ORIG_REF_NAME==design_1_axis_register_slice_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_20/design_1_xlslice_0_20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_20 || ORIG_REF_NAME==design_1_xlslice_0_20} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_26/design_1_sync_0_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_26 || ORIG_REF_NAME==design_1_sync_0_26} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_1_8/design_1_sync_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_1_8 || ORIG_REF_NAME==design_1_sync_1_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_21/design_1_xlconstant_0_21.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_21 || ORIG_REF_NAME==design_1_xlconstant_0_21} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_10/design_1_util_vector_logic_2_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_10 || ORIG_REF_NAME==design_1_util_vector_logic_2_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_34/design_1_util_vector_logic_0_34.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_34 || ORIG_REF_NAME==design_1_util_vector_logic_0_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_33/design_1_util_vector_logic_1_33.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_33 || ORIG_REF_NAME==design_1_util_vector_logic_1_33} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_8/design_1_axis_broadcaster_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_8 || ORIG_REF_NAME==design_1_axis_broadcaster_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_loopback_gpio_4/design_1_loopback_gpio_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_loopback_gpio_4 || ORIG_REF_NAME==design_1_loopback_gpio_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_35/design_1_util_vector_logic_0_35.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_35 || ORIG_REF_NAME==design_1_util_vector_logic_0_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_34/design_1_util_vector_logic_1_34.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_34 || ORIG_REF_NAME==design_1_util_vector_logic_1_34} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_35/design_1_util_vector_logic_1_35.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_35 || ORIG_REF_NAME==design_1_util_vector_logic_1_35} -quiet] -quiet

# IP: bd/design_1/ip/design_1_localstart_gpio_7/design_1_localstart_gpio_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_localstart_gpio_7 || ORIG_REF_NAME==design_1_localstart_gpio_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sync_0_27/design_1_sync_0_27.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sync_0_27 || ORIG_REF_NAME==design_1_sync_0_27} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_22/design_1_xlconstant_0_22.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_22 || ORIG_REF_NAME==design_1_xlconstant_0_22} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_1_2/design_1_axis_register_slice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_1_2 || ORIG_REF_NAME==design_1_axis_register_slice_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_1_3/design_1_axis_register_slice_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_1_3 || ORIG_REF_NAME==design_1_axis_register_slice_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tlast_gen_v1_0_0_8/design_1_tlast_gen_v1_0_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tlast_gen_v1_0_0_8 || ORIG_REF_NAME==design_1_tlast_gen_v1_0_0_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_0/design_1_idle_packet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_0 || ORIG_REF_NAME==design_1_idle_packet_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_1/design_1_idle_packet_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_1 || ORIG_REF_NAME==design_1_idle_packet_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_2/design_1_idle_packet_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_2 || ORIG_REF_NAME==design_1_idle_packet_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_3/design_1_idle_packet_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_3 || ORIG_REF_NAME==design_1_idle_packet_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_counter_0_2/design_1_packet_counter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_counter_0_2 || ORIG_REF_NAME==design_1_packet_counter_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_counter_0_4/design_1_packet_counter_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_counter_0_4 || ORIG_REF_NAME==design_1_packet_counter_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_counter_0_1/design_1_packet_counter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_counter_0_1 || ORIG_REF_NAME==design_1_packet_counter_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_0/design_1_packet_detector_11AD_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_0 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_counter_0_3/design_1_packet_counter_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_counter_0_3 || ORIG_REF_NAME==design_1_packet_counter_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_5/design_1_idle_packet_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_5 || ORIG_REF_NAME==design_1_idle_packet_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_7/design_1_idle_packet_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_7 || ORIG_REF_NAME==design_1_idle_packet_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_4/design_1_idle_packet_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_4 || ORIG_REF_NAME==design_1_idle_packet_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_idle_packet_0_6/design_1_idle_packet_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_idle_packet_0_6 || ORIG_REF_NAME==design_1_idle_packet_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SIVERS_gpio_0_0/design_1_SIVERS_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SIVERS_gpio_0_0 || ORIG_REF_NAME==design_1_SIVERS_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_1/design_1_packet_detector_11AD_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_1 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_3/design_1_packet_detector_11AD_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_3 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_boundary_detector_0_0/design_1_boundary_detector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_boundary_detector_0_0 || ORIG_REF_NAME==design_1_boundary_detector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SIVERS_gpio_0_1/design_1_SIVERS_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SIVERS_gpio_0_1 || ORIG_REF_NAME==design_1_SIVERS_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packet_detector_11AD_0_2/design_1_packet_detector_11AD_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_packet_detector_11AD_0_2 || ORIG_REF_NAME==design_1_packet_detector_11AD_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_46/design_1_util_vector_logic_0_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_46 || ORIG_REF_NAME==design_1_util_vector_logic_0_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_47/design_1_util_vector_logic_0_47.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_47 || ORIG_REF_NAME==design_1_util_vector_logic_0_47} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_46/design_1_util_vector_logic_1_46.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_46 || ORIG_REF_NAME==design_1_util_vector_logic_1_46} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_5/design_1_axis_dwidth_converter_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_5 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_6/design_1_axis_dwidth_converter_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_6 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_1_3/design_1_axis_dwidth_converter_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_1_3 || ORIG_REF_NAME==design_1_axis_dwidth_converter_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_2_0/design_1_axis_dwidth_converter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_2_0 || ORIG_REF_NAME==design_1_axis_dwidth_converter_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_3_0/design_1_axis_dwidth_converter_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_3_0 || ORIG_REF_NAME==design_1_axis_dwidth_converter_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_3_1/design_1_axis_dwidth_converter_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_3_1 || ORIG_REF_NAME==design_1_axis_dwidth_converter_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_3_2/design_1_axis_dwidth_converter_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_3_2 || ORIG_REF_NAME==design_1_axis_dwidth_converter_3_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_3_3/design_1_axis_dwidth_converter_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_3_3 || ORIG_REF_NAME==design_1_axis_dwidth_converter_3_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_combiner_3_0/design_1_axis_combiner_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_combiner_3_0 || ORIG_REF_NAME==design_1_axis_combiner_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_combiner_1_0/design_1_axis_combiner_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_combiner_1_0 || ORIG_REF_NAME==design_1_axis_combiner_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_combiner_0_4/design_1_axis_combiner_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_combiner_0_4 || ORIG_REF_NAME==design_1_axis_combiner_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tlast_gen_v1_0_3_0/design_1_tlast_gen_v1_0_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tlast_gen_v1_0_3_0 || ORIG_REF_NAME==design_1_tlast_gen_v1_0_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_3_0/design_1_axis_data_fifo_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_3_0 || ORIG_REF_NAME==design_1_axis_data_fifo_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_13/design_1_axis_data_fifo_0_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_13 || ORIG_REF_NAME==design_1_axis_data_fifo_0_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tlast_gen_v1_0_0_9/design_1_tlast_gen_v1_0_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tlast_gen_v1_0_0_9 || ORIG_REF_NAME==design_1_tlast_gen_v1_0_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tlast_gen_v1_0_1_0/design_1_tlast_gen_v1_0_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tlast_gen_v1_0_1_0 || ORIG_REF_NAME==design_1_tlast_gen_v1_0_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_10/design_1_axis_data_fifo_1_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_10 || ORIG_REF_NAME==design_1_axis_data_fifo_1_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_23 || ORIG_REF_NAME==design_1_axis_register_slice_0_23} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_24/design_1_axis_register_slice_0_24.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_24 || ORIG_REF_NAME==design_1_axis_register_slice_0_24} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_26/design_1_axis_register_slice_0_26.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_26 || ORIG_REF_NAME==design_1_axis_register_slice_0_26} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_27/design_1_axis_register_slice_0_27.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_27 || ORIG_REF_NAME==design_1_axis_register_slice_0_27} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_28/design_1_axis_register_slice_0_28.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_28 || ORIG_REF_NAME==design_1_axis_register_slice_0_28} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_29/design_1_axis_register_slice_0_29.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_29 || ORIG_REF_NAME==design_1_axis_register_slice_0_29} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_30/design_1_axis_register_slice_0_30.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_30 || ORIG_REF_NAME==design_1_axis_register_slice_0_30} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_register_slice_0_25/design_1_axis_register_slice_0_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_register_slice_0_25 || ORIG_REF_NAME==design_1_axis_register_slice_0_25} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_7/design_1_axis_dwidth_converter_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_7 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_9/design_1_axis_dwidth_converter_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_9 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_10/design_1_axis_dwidth_converter_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_10 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dwidth_converter_0_11/design_1_axis_dwidth_converter_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_dwidth_converter_0_11 || ORIG_REF_NAME==design_1_axis_dwidth_converter_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_3_0/design_1_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_3_0 || ORIG_REF_NAME==design_1_tier2_xbar_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
