# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documentos/RFSoc/MTS_4x4_PD_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23.xci
# IP: The module: 'design_1_axis_register_slice_0_23' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documentos/RFSoc/MTS_4x4_PD_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_register_slice_0_23'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoc/MTS_4x4_PD_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_register_slice_0_23'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rafael/Documentos/RFSoc/MTS_4x4_PD_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23.xci
# IP: The module: 'design_1_axis_register_slice_0_23' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rafael/Documentos/RFSoc/MTS_4x4_PD_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_register_slice_0_23'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoc/MTS_4x4_PD_nw/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_axis_register_slice_0_23/design_1_axis_register_slice_0_23_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_register_slice_0_23'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
