# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_TX_Block_AP_0_0/design_1_TX_Block_AP_0_0.xci
# IP: The module: 'design_1_TX_Block_AP_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_broadcaster_0 || ORIG_REF_NAME==axis_broadcaster_0} -quiet] -quiet

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_1 || ORIG_REF_NAME==axis_data_fifo_1} -quiet] -quiet

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/constrs_1/new/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_TX_Block_AP_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0_ooc.xdc

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/design_1_TX_Block_AP_0_0/design_1_TX_Block_AP_0_0.xci
# IP: The module: 'design_1_TX_Block_AP_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_broadcaster_0 || ORIG_REF_NAME==axis_broadcaster_0} -quiet] -quiet

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_data_fifo_1/axis_data_fifo_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_1 || ORIG_REF_NAME==axis_data_fifo_1} -quiet] -quiet

# IP: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/constrs_1/new/constraints.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_TX_Block_AP_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rafael/Documentos/RFSoC_Vivado/MTS_4x4_PD_AP/Basic_1x1.srcs/sources_1/bd/design_1/ip/edit_TX_Block_AP_v1_0.srcs/sources_1/ip/axis_broadcaster_0/axis_broadcaster_0_ooc.xdc
